### ISSUE TITLE
Block on file open request

### ISSUE THREAD

**Issue by JuniorJPDJ** [nktknshn/tgmount#2]
Hi,
When I try to open file there's infinite (or just long enough for me to stop waiting) block of any program trying to do so.
Not even reading file, just opening.
There's an example:
![Screenshot_20200816_010417](https://user-images.githubusercontent.com/7334549/90323060-6a340200-df5c-11ea-9409-1fe13cb04ad7.png)

**Comment by nktknshn** [comment]
Hey! Thank you for reporting the issue. I fixed it in the last commit. Please try and tell if it works now

**Comment by JuniorJPDJ** [comment]
Yes, thanks, It works very good ;)
