### ISSUE TITLE
New file doesn't trigger inotify event

### ISSUE THREAD

**Issue by JuniorJPDJ** [nktknshn/tgmount#5]
![Screenshot_20200826_235628](https://user-images.githubusercontent.com/7334549/91361016-c407b800-e7f7-11ea-825d-17957aed1cd2.png)

**Comment by nktknshn** [comment]
It seems it's not currently possible to trigger inotify events because "notify systems of the Linux kernel do not work with filesystems in userspace". The problem is explained in official repo of libfuse here:
https://github.com/libfuse/libfuse/wiki/Fsnotify-and-FUSE

**Comment by JuniorJPDJ** [comment]
Pretty sad, but I'll find workaround ;/
